<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="5" total="12" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-10T13:10:35 IST" name="Suite" finished-at="2024-05-10T13:12:44 IST" duration-ms="128921">
    <groups>
      <group name="Smoke">
        <method signature="SavvyLoginTest.loginWithValidCredentials()[pri:0, instance:com.chargeSavvy.SavvyLoginTest@3e27ba32]" name="loginWithValidCredentials" class="com.chargeSavvy.SavvyLoginTest"/>
        <method signature="SearchMerchantTest.verifyBergModelRequireErrMsg()[pri:0, instance:com.chargeSavvy.SearchMerchantTest@57a78e3]" name="verifyBergModelRequireErrMsg" class="com.chargeSavvy.SearchMerchantTest"/>
        <method signature="SearchMerchantTest.verifyIpAddressErrMsgWhenIpAddressFieldIsEmpty()[pri:0, instance:com.chargeSavvy.SearchMerchantTest@57a78e3]" name="verifyIpAddressErrMsgWhenIpAddressFieldIsEmpty" class="com.chargeSavvy.SearchMerchantTest"/>
        <method signature="SearchMerchantTest.verifySomethingWentWrongErrMsgWhenPortNumberFieldIsEmpty()[pri:0, instance:com.chargeSavvy.SearchMerchantTest@57a78e3]" name="verifySomethingWentWrongErrMsgWhenPortNumberFieldIsEmpty" class="com.chargeSavvy.SearchMerchantTest"/>
      </group> <!-- Smoke -->
    </groups>
    <test started-at="2024-05-10T13:10:35 IST" name="Test" finished-at="2024-05-10T13:12:44 IST" duration-ms="128921">
      <class name="com.chargeSavvy.SavvyLoginTest">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.chargeSavvy.SavvyLoginTest@3e27ba32]" started-at="2024-05-10T13:10:36 IST" name="setUp" finished-at="2024-05-10T13:10:50 IST" duration-ms="14346" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://qa.mychargesavvy.com/auth/login]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method retried="true" signature="loginWithValidCredentials()[pri:0, instance:com.chargeSavvy.SavvyLoginTest@3e27ba32]" started-at="2024-05-10T13:10:50 IST" name="loginWithValidCredentials" finished-at="2024-05-10T13:10:50 IST" duration-ms="364" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Text does not match! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Text does not match! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.chargeSavvy.SavvyLoginTest.loginWithValidCredentials(SavvyLoginTest.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithValidCredentials -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.chargeSavvy.SavvyLoginTest@3e27ba32]" started-at="2024-05-10T13:10:50 IST" name="closeBrowser" finished-at="2024-05-10T13:10:51 IST" duration-ms="431" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.chargeSavvy.SavvyLoginTest@3e27ba32]" started-at="2024-05-10T13:10:51 IST" name="setUp" finished-at="2024-05-10T13:10:56 IST" duration-ms="4674" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://qa.mychargesavvy.com/auth/login]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method retried="true" signature="loginWithValidCredentials()[pri:0, instance:com.chargeSavvy.SavvyLoginTest@3e27ba32]" started-at="2024-05-10T13:10:56 IST" name="loginWithValidCredentials" finished-at="2024-05-10T13:10:56 IST" duration-ms="426" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Text does not match! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Text does not match! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.chargeSavvy.SavvyLoginTest.loginWithValidCredentials(SavvyLoginTest.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithValidCredentials -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.chargeSavvy.SavvyLoginTest@3e27ba32]" started-at="2024-05-10T13:10:56 IST" name="closeBrowser" finished-at="2024-05-10T13:10:56 IST" duration-ms="414" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.chargeSavvy.SavvyLoginTest@3e27ba32]" started-at="2024-05-10T13:10:56 IST" name="setUp" finished-at="2024-05-10T13:11:01 IST" duration-ms="4746" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://qa.mychargesavvy.com/auth/login]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method retried="true" signature="loginWithValidCredentials()[pri:0, instance:com.chargeSavvy.SavvyLoginTest@3e27ba32]" started-at="2024-05-10T13:11:01 IST" name="loginWithValidCredentials" finished-at="2024-05-10T13:11:01 IST" duration-ms="191" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Text does not match! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Text does not match! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.chargeSavvy.SavvyLoginTest.loginWithValidCredentials(SavvyLoginTest.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithValidCredentials -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.chargeSavvy.SavvyLoginTest@3e27ba32]" started-at="2024-05-10T13:11:01 IST" name="closeBrowser" finished-at="2024-05-10T13:11:02 IST" duration-ms="345" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.chargeSavvy.SavvyLoginTest@3e27ba32]" started-at="2024-05-10T13:11:02 IST" name="setUp" finished-at="2024-05-10T13:11:13 IST" duration-ms="11237" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://qa.mychargesavvy.com/auth/login]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginWithValidCredentials()[pri:0, instance:com.chargeSavvy.SavvyLoginTest@3e27ba32]" started-at="2024-05-10T13:11:13 IST" name="loginWithValidCredentials" finished-at="2024-05-10T13:11:13 IST" duration-ms="175" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Text does not match! expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Text does not match! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.chargeSavvy.SavvyLoginTest.loginWithValidCredentials(SavvyLoginTest.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithValidCredentials -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.chargeSavvy.SavvyLoginTest@3e27ba32]" started-at="2024-05-10T13:11:13 IST" name="closeBrowser" finished-at="2024-05-10T13:11:13 IST" duration-ms="319" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.chargeSavvy.SavvyLoginTest -->
      <class name="com.chargeSavvy.SearchMerchantTest">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.chargeSavvy.SearchMerchantTest@57a78e3]" started-at="2024-05-10T13:11:14 IST" name="setup" finished-at="2024-05-10T13:11:27 IST" duration-ms="13506" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://qa.mychargesavvy.com/auth/login]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyBergModelRequireErrMsg()[pri:0, instance:com.chargeSavvy.SearchMerchantTest@57a78e3]" started-at="2024-05-10T13:11:27 IST" name="verifyBergModelRequireErrMsg" finished-at="2024-05-10T13:11:47 IST" duration-ms="19474" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyBergModelRequireErrMsg -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.chargeSavvy.SearchMerchantTest@57a78e3]" started-at="2024-05-10T13:11:47 IST" name="closeBrowser" finished-at="2024-05-10T13:11:47 IST" duration-ms="491" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.chargeSavvy.SearchMerchantTest@57a78e3]" started-at="2024-05-10T13:11:47 IST" name="setup" finished-at="2024-05-10T13:12:00 IST" duration-ms="12714" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://qa.mychargesavvy.com/auth/login]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyIpAddressErrMsgWhenIpAddressFieldIsEmpty()[pri:0, instance:com.chargeSavvy.SearchMerchantTest@57a78e3]" started-at="2024-05-10T13:12:00 IST" name="verifyIpAddressErrMsgWhenIpAddressFieldIsEmpty" finished-at="2024-05-10T13:12:19 IST" duration-ms="19132" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyIpAddressErrMsgWhenIpAddressFieldIsEmpty -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.chargeSavvy.SearchMerchantTest@57a78e3]" started-at="2024-05-10T13:12:19 IST" name="closeBrowser" finished-at="2024-05-10T13:12:20 IST" duration-ms="727" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.chargeSavvy.SearchMerchantTest@57a78e3]" started-at="2024-05-10T13:12:20 IST" name="setup" finished-at="2024-05-10T13:12:23 IST" duration-ms="3786" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://qa.mychargesavvy.com/auth/login]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifySomethingWentWrongErrMsgWhenPortNumberFieldIsEmpty()[pri:0, instance:com.chargeSavvy.SearchMerchantTest@57a78e3]" started-at="2024-05-10T13:12:23 IST" name="verifySomethingWentWrongErrMsgWhenPortNumberFieldIsEmpty" finished-at="2024-05-10T13:12:44 IST" duration-ms="20359" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySomethingWentWrongErrMsgWhenPortNumberFieldIsEmpty -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:com.chargeSavvy.SearchMerchantTest@57a78e3]" started-at="2024-05-10T13:12:44 IST" name="closeBrowser" finished-at="2024-05-10T13:12:44 IST" duration-ms="617" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.chargeSavvy.SearchMerchantTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
